---

version: 1
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'merge-strategy: rebase'
      - 'type: dependencies'
      - 'git-submodule'
