on:
  issue_comment:
    types:
      - created
jobs:
  container-tests:
    runs-on: ubuntu-20.04
    name: "Container-tests: ${{ matrix.version }} - ${{ matrix.os_test }}"
    strategy:
      fail-fast: false
      matrix:
        version: [ "1.20", "1.22", "1.22-micro" ]
        os_test: [ "fedora", "centos7", "rhel7", "rhel8", "rhel9", "c9s", "rhel9-unsubscribed" ]
        test_case: [ "container" ]

    if: |
      github.event.issue.pull_request
      && (contains(github.event.comment.body, '[test]') || contains(github.event.comment.body, '[test-all]'))
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Schedule tests for ${{ matrix.version }} - ${{ matrix.os_test }}
        uses: sclorg/tfaga-wrapper@inherit_secrets
        with:
          os_test: ${{ matrix.os_test }}
          test_case: ${{ matrix.test_case }}
          version: ${{ matrix.version }}
