on:
  push
jobs:
  container-tests:
    runs-on: ubuntu-20.04
    name: "Container tests: ${{ matrix.version }} - ${{ matrix.context }}"
    strategy:
      fail-fast: false
      matrix:
        version: [ "1.18", "1.20", "1.22" ]
        os_test: [ "fedora", "centos7", "c9s"]
        include:
          - tmt_plan: "fedora"
            os_test: "fedora"
            context: "Fedora"
            compose: "Fedora-latest"
            api_key: "TF_PUBLIC_API_KEY"
            branch: "main"
            tmt_repo: "https://github.com/sclorg/sclorg-testing-farm"
          - tmt_plan: "centos7"
            os_test: "centos7"
            context: "CentOS7"
            compose: "CentOS-7"
            api_key: "TF_PUBLIC_API_KEY"
            branch: "main"
            tmt_repo: "https://github.com/sclorg/sclorg-testing-farm"
          - tmt_plan: "c9s"
            os_test: "c9s"
            context: "CentOS Stream 9"
            compose: "CentOS-Stream-9"
            api_key: "TF_PUBLIC_API_KEY"
            branch: "main"
            tmt_repo: "https://github.com/sclorg/sclorg-testing-farm"

    steps:
      - name: Schedule tests for ${{ matrix.version }} - ${{ matrix.context }}
        uses: zmiklank/testing-farm-as-github-action@exit_on_sha_fail
        with:
          api_key: ${{ secrets[matrix.api_key] }}
          git_url: ${{ matrix.tmt_repo }}
          git_ref: ${{ matrix.branch }}
          tf_scope: ${{ matrix.tf_scope }}
          tmt_plan_regex: ${{ matrix.tmt_plan }}
          pull_request_status_name: "${{ matrix.context }} - ${{ matrix.version }}"
          variables: "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY;REPO_NAME=$GITHUB_REPOSITORY;PR_NUMBER=${{ github.event.issue.number }};SINGLE_VERSION=${{ matrix.version }};OS=${{ matrix.os_test }};TEST_NAME=test"
          compose: ${{ matrix.compose }}
